# Default colors
[colors.primary]
background = '#191724'
foreground = '#e0def4'

# Normal colors
[colors.normal]
black = '#191724'
red = '#A71D31'
green = '#237161'
yellow = '#E4BA00'
blue = '#0f5187'
magenta = '#c4a7e7'
cyan = '#9ccfd8'
white = '#e0def4'

# Bright colors
[colors.bright]
black = '#6e6a86'
red = '#D4284A'
green = '#2D9B7F'
yellow = '#FFD633'
blue = '#1A6BB3'
magenta = '#D4BFEF'
cyan = '#B8E6EE'
white = '#e0def4'
